

const fabricData = [
  {
  name: 'Windowpane Dog Bandana',
  length: '16"',
  width:  '11"',
  material: 'canvas',
  designer: 'Suzanne Mozes',
  color: 'pink',
  category: 'dog',
  category2: 'dog accessories',
  image: 'https://imgur.com/qFF0Ww2.jpg' ,
  stock: '10',
  price: '10',
  alt: 'black and white pink bandana',
},
{
  name: 'Floral Dog Bandana',
  length: '16"',
  width:  '11"',
  material: 'canvas',
  designer: 'Suzanne Mozes',
  color: 'pink',
  category: 'dog',
  category2: 'dog accessories',
  image: 'https://imgur.com/xau5UUX.jpg' ,
  stock: '10',
  price: '10',
  alt: 'floral bandana',
},
{
  name: 'Sharks Dog Bandana',
  length: '16"',
  width:  '11"',
  material: 'cotton',
  designer: 'Suzanne Mozes',
  color: 'blue, white',
  category: 'dog',
  category2: 'dog accessories',
  image: 'https://imgur.com/AbjOAQw.jpg' ,
  stock: '10',
  price: '10',
  alt: 'shark patterned bandana',
},
{
  name: 'Beetle Dog Bandana',
  length: '16"',
  width:  '11"',
  material: 'canvas',
  designer: 'Suzanne Mozes',
  color: 'green, white',
  category: 'dog',
  category2: 'dog accessories',
  image: 'https://imgur.com/0WGmpB5.jpg' ,
  stock: '10',
  price: '10',
  alt: 'bandana',
},
{
  name: 'Boho Dog Bandana',
  length: '16"',
  width:  '11"',
  material: 'canvas',
  designer: 'Suzanne Mozes',
  color: 'black, white',
  category: 'dog',
  category2: 'dog accessories',
  image: 'https://imgur.com/yHsV1eM.jpg' ,
  stock: '10',
  price: '10',
  alt: 'floral bandana',
},
{
    name: 'Piparo Fushia',
    length: '42 inches',
    width:  '45 inches',
    material: 'jacquard',
    designer: 'James Hare',
    color: 'pink',
    category: 'remnant',
    category2: 'upholstery',
    image: 'https://imgur.com/ou4pbe0.jpg',
    stock: '1',
    price: '85',
    alt: 'pink puzzlepiece pattern upholstery remant'
},
{
  name: 'Fuschia Valentine Pillow',
  length: '10',
  width:  '6',
  material: 'silk',
  designer: 'Suzanne Mozes',
  color: 'pink, silver',
  category: 'home',
  category2: 'pillow',
  image: 'https://imgur.com/nP3HpCI.jpg',
  stock: '1',
  price: '45',
  alt: 'two small pillows on table'
},
{
  name: 'Four Winds Quilt',
  length: '96',
  width:  '72',
  material: 'organic cotton',
  designer: 'Fancy Tiger Crafts',
  color: 'blue, beige',
  category: 'home',
  category2: 'bedding',
  image: 'https://imgur.com/UVzjSs4.jpg',
  stock: '1',
  price: '300',
  alt: 'geese patterned quilt on bed'
},
{
  name: 'Green Velvet Cocktail Dress',
  length: 'n/a',
  width:  'n/a',
  material: 'poly',
  designer: 'Suzanne Mozes',
  color: 'emerald green',
  category: 'garment',
  category2: 'dress',
  image: 'https://imgur.com/L1iiDYu.jpg',
  stock: '1',
  price: '100',
  alt: 'ryan wearing green dress'
},
{
  name: 'Infant Christening Jumper',
  length: 'n/a',
  width:  'n/a',
  material: 'cotton, silk',
  designer: 'Butterick, Suzanne Mozes',
  color: 'white',
  category: 'garment',
  category2: 'child',
  image: 'https://imgur.com/Si9GTC8.jpg',
  stock: '1',
  price: "500",
  alt: 'woman holding baby'
},
{
  name: 'Italian White Embroidered Tablecloth',
  length: '55',
  width:  '45',
  material: 'linen',
  designer: 'Suzanne Mozes',
  color: 'white',
  category: 'home',
  category2: 'table',
  image: 'https://imgur.com/ElusPEl.jpg',
  stock: '1',
  price: '200',
  alt: 'white linen corner of tablecloth'
},
{
  name: 'Child Bloomers',
  length: 'n/a',
  width:  'n/a',
  material: 'linen',
  designer: 'Suzanne Mozes',
  color: 'rustic yellow',
  category: 'garment',
  category2: 'child',
  image: 'https://imgur.com/bokUn1E.jpg',
  stock: '4',
  price: '150',
  alt: 'baby bloomers'
},
{
  name: '4th of July Button Down',
  length: 'n/a',
  width:  'n/a',
  material: 'linen',
  designer: 'Paper Theory, Suzanne Mozes',
  color: 'striped red and blue',
  category: 'garment',
  category2: 'men',
  image: 'https://imgur.com/YBMBEY3.jpg',
  stock: '1',
  price: '300',
  alt: 'man in shirt'
},
{
  name: 'Koala Bear Hoodie',
  length: 'n/a',
  width:  'n/a',
  material: 'terry',
  designer: 'Butterick, Suzanne Mozes',
  color: 'gray',
  category: 'garment',
  category2: 'child',
  image: 'https://imgur.com/V6KJX65.jpg',
  stock: '1',
  price: '50',
  alt: 'child on beach'
},
{
  name: 'Piparo',
  length: '28',
  width:  '55',
  material: 'silk',
  designer: 'James',
  color: 'silver',
  category: 'remnant',
  category2: 'upholstery',
  image: 'https://imgur.com/8yqxvur.jpg',
  stock: '1',
  price: '20',
  alt: 'puzzle piece pattern'
},
{
name: 'Piparo',
length: '28',
width:  '55',
material: 'silk',
designer: 'James',
color: 'pink',
category: 'remnant',
category2: 'upholstery',
image: 'https://imgur.com/ou4pbe0.jpg',
stock: '1',
price: '20',
alt: 'puzzle piece pattern'
},
{
  name: 'Baby Bloomers',
  length: 'n/a',
  width:  'n/a',
  material: 'linen',
  designer: 'Butterick, Suzanne Mozes',
  color: 'blue',
  category: 'garment',
  category2: 'child',
  image: 'https://imgur.com/B8G1nCX.jpg',
  stock: '1',
  price: '200',
  alt: 'blue bloomers'
},
{
  name: 'Summer Bag',
  length: '10',
  width:  '12',
  material: 'canvas, denim, leather',
  designer: 'Suzanne Mozes',
  color: 'white, black, brown',
  category: 'garment',
  category2: 'accessories',
  image: 'https://imgur.com/6cYBjsj.jpg',
  stock: '1',
  price: '95',
  alt: 'bag'
},
{
  name: 'Striated Faux Fur',
  length: '15',
  width:  '12',
  material: 'poly, silk',
  designer: 'James Hare',
  color: 'gold',
  category: 'remant',
  category2: 'upholstery',
  image: 'https://imgur.com/55WDeHk.jpg',
  stock: '1',
  price: '15',
  alt: 'faux gold fur'
},
{
  name: 'Striated Faux Fur',
  length: '15',
  width:  '12',
  material: 'poly, silk',
  designer: 'James Hare',
  color: 'purple',
  category: 'remant',
  category2: 'upholstery',
  image: 'https://imgur.com/EMAp9re.jpg',
  stock: '1',
  price: '15',
  alt: 'faux gold fur'
},
{
  name: 'Striated Faux Fur',
  length: '15',
  width:  '12',
  material: 'poly, silk',
  designer: 'James Hare',
  color: 'red',
  category: 'remant',
  category2: 'upholstery',
  image: 'https://imgur.com/RQnvyzO.jpg',
  stock: '1',
  price: '15',
  alt: 'faux gold fur'
},
{
  name: 'Zippered Velvet Pillow',
  length: '18',
  width:  '16',
  material: 'poly, silk',
  designer: 'Suzanne Mozes',
  color: 'chartreuse',
  category: 'home',
  category2: 'pillow',
  image: 'https://imgur.com/nCgsJrw.jpg',
  stock: '1',
  price: '80',
  alt: 'pillow on side'
},
{
  name: 'Zippered Floral Silk Pillow',
  length: '16',
  width:  '16',
  material: 'poly, silk',
  designer: 'Suzanne Mozes',
  color: 'cream, gold, silver',
  category: 'home',
  category2: 'pillow',
  image: 'https://imgur.com/zy9gBvV.jpg',
  stock: '2',
  price: '80',
  alt: 'pillow on side'
},
{
  name: 'Zippered Diamond Patterned Pillow',
  length: '16',
  width:  '16',
  material: 'poly, cotton',
  designer: 'Suzanne Mozes',
  color: 'white, black',
  category: 'home',
  category2: 'pillow',
  image: 'https://imgur.com/pXH3Z2Y.jpg',
  stock: '2',
  price: '80',
  alt: 'pillow on side'
},
{
  name: 'Zippered Embroidered Lumbar Pillow',
  length: '18',
  width:  '11',
  material: 'poly, cotton',
  designer: 'Suzanne Mozes',
  color: 'blue, green, beige',
  category: 'home',
  category2: 'pillow',
  image: 'https://imgur.com/XHp5oga.jpg',
  stock: '2',
  price: '80',
  alt: 'pillow on side'
},
{
  name: 'Trio of Silk Gold Multi-Patterned Pillows',
  length: 'varies',
  width:  'varies',
  material: 'silk',
  designer: 'Suzanne Mozes',
  color: 'gold',
  category: 'home',
  category2: 'pillow',
  image: 'https://imgur.com/qpishZq.jpg',
  stock: '1',
  price: '150',
  alt: 'three pillows on couch'
},
{
  name: 'Tiffany Handstitched Napkins',
  length: '18',
  width:  '18',
  material: 'organic linen',
  designer: 'Suzanne Mozes',
  color: 'robin egg blue',
  category: 'home',
  category2: 'table',
  image: 'https://imgur.com/jEyJYJd.jpg',
  stock: '100',
  price: '50',
  alt: 'pile of folded napkins'
},
{
  name: 'Denim Jacket',
  length: '18',
  width:  'n/a',
  material: 'denim, flannel',
  designer: 'Closet Core Patterns, Suzanne Mozes',
  color: 'blue, plaid',
  category: 'dog',
  category2: 'dog accessories',
  image: 'https://imgur.com/YA8j2d1.jpg',
  stock: '1',
  price: '100',
  alt: 'dog in denim coat'
},
{
  name: 'Diamond Pattern Dog Bed',
  length: '3 feet',
  width:  '2 feet',
  material: 'canvas',
  designer: 'Suzanne Mozes',
  color: 'gray, white',
  category: 'dog',
  category2: 'bedding',
  image: 'https://imgur.com/Ly4q66x.jpg',
  stock: '1',
  price: '85',
  alt: 'dog on bed'
},
{
  name: 'Newborn Leggings',
  length: 'n/a',
  width:  'n/a',
  material: 'organic jersey',
  designer: 'Suzanne Mozes',
  color: 'varies',
  category: 'child',
  category2: 'pants',
  image: 'https://imgur.com/md6Rqo7.jpg',
  stock: '30',
  price: '20',
  alt: 'baby leggings'
},
{
  name: 'Pomegranite Tablecloth',
  length: '45',
  width:  '45',
  material: 'linen',
  designer: 'unknown',
  color: 'white, green, blue, red, yellow',
  category: 'home',
  category2: 'table',
  image: 'https://imgur.com/CaRFzMS.jpg',
  stock: '1',
  price: '55',
  alt: ''
},
{
  name: 'Mixed Bag: Reds',
  length: '1 yard',
  width:  '44"',
  material: 'quilting cottons',
  designer: 'varies',
  color: 'reds, pinks, peaches',
  category: 'remnant',
  category2: 'surprise',
  image: 'https://imgur.com/gBU3Mdo.jpg',
  stock: '1',
  price: '30',
  alt: 'varied prints'
},
{
  name: 'Mixed Bag: Geo',
  length: '1 yard',
  width:  '44"',
  material: 'quilting cottons',
  designer: 'varies',
  color: 'purple, black, gray',
  category: 'remnant',
  category2: 'surprise',
  image: 'https://imgur.com/nEIY2AE.jpg',
  stock: '1',
  price: '30',
  alt: 'varied prints'
},
{
  name: 'Mixed Bag: Boho',
  length: '1 yard',
  width:  '44"',
  material: 'quilting cottons',
  designer: 'varies',
  color: 'black, white, beige',
  category: 'remnant',
  category2: 'surprise',
  image: 'https://imgur.com/b52YOXO.jpg',
  stock: '1',
  price: '30',
  alt: 'varied prints'
},
{
  name: 'Mixed Bag: Florals',
  length: '1 yard',
  width:  '44"',
  material: 'quilting cottons',
  designer: 'varies',
  color: 'pink, purple, blue, beige',
  category: 'remnant',
  category2: 'surprise',
  image: 'https://imgur.com/MXbRNyF.jpg',
  stock: '1',
  price: '30',
  alt: 'varied prints'
},
{
  name: 'Mixed Bag: Camo',
  length: '1 yard',
  width:  '44"',
  material: 'quilting cottons',
  designer: 'varies',
  color: 'green, beige, brown',
  category: 'remnant',
  category2: 'surprise',
  image: 'https://imgur.com/faTXA0H.jpg',
  stock: '1',
  price: '30',
  alt: 'varied prints'
},
{
  name: 'Mixed Bag: Minimalistic',
  length: '1 yard',
  width:  '44"',
  material: 'quilting cottons',
  designer: 'varies',
  color: 'black, white',
  category: 'remnant',
  category2: 'surprise',
  image: 'https://imgur.com/iM9Ndiz.jpg',
  stock: '1',
  price: '30',
  alt: 'varied prints'
},
{
  name: 'Mixed Bag: Animals',
  length: '1 yard',
  width:  '44"',
  material: 'quilting cottons',
  designer: 'varies',
  color: 'black, beige, green blue',
  category: 'remnant',
  category2: 'surprise',
  image: 'https://imgur.com/nTObJHA.jpg',
  stock: '1',
  price: '30',
  alt: 'varied prints'
},
{
  name: 'Geo Abstract',
  length: '72',
  width:  '55',
  material: 'linen, cotton',
  designer: 'tbd',
  color: 'black, white',
  category: 'remnant',
  category2: 'upholstery',
  image: 'https://imgur.com/8fHLlpd.jpg',
  stock: '1',
  price: '55',
  alt: ''
},
{
  name: 'Sea Green Ikat',
  length: '60',
  width:  '55',
  material: 'canvas',
  designer: 'unknown',
  color: 'blue, beige',
  category: 'remant',
  category2: 'upholstery',
  image: 'https://imgur.com/h0MFUVf.jpg',
  stock: '1',
  price: '20',
  alt: ''
},

]

module.exports = fabricData